spring:
  rabbitmq:
    addresses: localhost:5672
    username: rmuser
    password: rmpassword
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2

